# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "shouanzhong-patch-test-workflow" ]
  pull_request:
    branches: [ "shouanzhong-patch-test-workflow" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Create file
      run: |
        touch file1.txt
        echo "This is file1.txt" >> file1.txt # 如果需要，可以添加内容到文件
        echo $(date) >> file1.txt

      # 配置git
    - name: Config git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "github"
        git remote set-url origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"
        echo git remote set-url origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"
        git pull --rebase

    # 更新仓库
    - name: Update repo
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add file1.txt
        git commit -m "auto update"
        git push -u origin

